projectwife/tesitoo-opencart

api/v1/catalog/controller/product/base/vendor_base.php
api/v1/catalog/controller/product/vendor.php
api/v1/system/library/errorcodes.php
catalog/controller/product/product.php
catalog/controller/product/vendor.php
catalog/language/english/product/product.php
catalog/language/english/product/vendor.php
catalog/model/catalog/product.php
catalog/model/catalog/vendor.php
catalog/view/theme/default/template/product/vendor_info.tpl
catalog/view/theme/default/template/product/vendor_list.tpl

Route: product/vendor lists all vendors
Route: product/vendor/{id} lists specific vendor details
Route: product/vendor/{id}/products lists vendors products the same as displayed in category products
output from route product/vendor (showing all vendors)
```javascript
{
"vendors": [
{
"vendor_id": 3,
"user_id": 2,
"username": "user",
"name": "Test Vendor",
"thumb": null,
"telephone": "5555551234",
"fax": "",
"company": "",
"description": "Test",
"email": "user@example.com",
"firstname": "John",
"lastname": "Doe",
"address": {
"address_1": "1234 Awesome Drive",
"address_2": "",
"city": "Kansas City",
"postcode": "64161",
"country": {
"country_id": "223",
"name": "United States",
"iso_code_2": "US",
"iso_code_3": "USA",
"address_format": "{firstname} …
```

Added public view vendor endpoints

---

api/v1/catalog/controller/admin/base/login_base.php
api/v1/catalog/controller/admin/login.php
api/v1/index.php

Asif's vendor login
POST: admin/login - parameters: username, password

Vendor login

---

api/v1/catalog/controller/product/base/vendor_base.php
api/v1/index.php
api/v1/system/library/errorcodes.php

Added error responses if vendor or vendors not found
Fixes issue #5

Vendor error responses

---

api/v1/catalog/controller/vendor/register.php
api/v1/system/library/errorcodes.php

Edit order

---

admin/controller/common/forgotten.php
admin/controller/marketing/contact.php
admin/model/marketing/affiliate.php
admin/model/sale/customer.php
admin/model/sale/return.php
admin/model/sale/voucher.php
catalog/controller/account/forgotten.php
catalog/controller/affiliate/forgotten.php
catalog/controller/information/contact.php
catalog/model/account/customer.php
catalog/model/affiliate/affiliate.php
catalog/model/catalog/review.php
catalog/model/checkout/order.php
catalog/model/checkout/voucher.php
catalog/model/openbay/ebay_order.php
system/library/ebay.php
system/library/openbay.php

(https://github.com/opencart/opencart/issues/2887)

Fix SMTP Host -> Hostname issue

---

admin/controller/common/forgotten.php
admin/controller/marketing/contact.php
admin/model/marketing/affiliate.php
admin/model/sale/customer.php
admin/model/sale/return.php
admin/model/sale/voucher.php
catalog/controller/account/forgotten.php
catalog/controller/affiliate/forgotten.php
catalog/controller/information/contact.php
catalog/model/account/customer.php
catalog/model/affiliate/affiliate.php
catalog/model/catalog/review.php
catalog/model/checkout/order.php
catalog/model/checkout/voucher.php
catalog/model/openbay/ebay_order.php
system/library/ebay.php
system/library/openbay.php
vqmod/xml/smtp_hostname.xml

Use VQmod to fix issue instead of directly changing core OpenCart files.

Fix smtp host

---

vqmod/xml/mvd_fixes_for_tesitoo_mobile_web.xml

to bring forms more in line with requested available data fields.

Fixes for registration, sign-up, edit screens

---

vqmod/xml/waabay_mvd_core_20160101_.xml

message to admin as well as to vendor.

Notifications: send copies of new order message and history order

---

admin/language/english/mail/email_notification.php
api/v1/catalog/controller/vendor/order_product.php
vqmod/xml/editable_order_status.xml

(cancelled, shipped, complete).

Implement admin notifications for vendor order updates via API

---

vqmod/xml/add_location_product_page.xml

('location', a plain text field of each product, is already usable by admin and vendors.)

Show product location on product page (for buyers).

---

catalog/controller/checkout/success.php
catalog/language/english/checkout/success.php
catalog/view/theme/atr374opc2101/stylesheet/stylesheet.css

Change link styling on the checkout success page so that the links are more clear.

Make text of checkout success page more relevant for Tesitoo.

---

admin/language/english/catalog/vendor.php
admin/language/english/user/vdi_user_password.php
api/v1/catalog/controller/product/base/vendor_base.php
api/v1/catalog/controller/product/vendor.php
api/v1/catalog/controller/vendor/order.php
api/v1/catalog/controller/vendor/order_product.php
api/v1/catalog/controller/vendor/products.php
api/v1/catalog/controller/vendor/profile.php
api/v1/catalog/controller/vendor/profile_image.php
api/v1/catalog/controller/vendor/register.php
catalog/controller/account/signup.php
catalog/language/english/account/signup.php
vqmod/xml/mvd_fixes_for_tesitoo_mobile_web.xml

Address, country, company, telephone fields are now optional in vendor registration API request.
(According to recent discussions on call / email.)
Company is set to '<first-name> <last-name>' if not specified.

Optional registration fields

---

admin/controller/catalog/vendor.php
admin/view/template/catalog/vdi_vendor_profile_form.tpl
admin/view/template/catalog/vendor_form.tpl

(Following removal of required fields in vendor profile API request.)

Remove required vendor profile editing form fields on web admin pages.

---

catalog/controller/product/product.php
catalog/view/theme/atr374opc2101/template/product/product.tpl

controller is shared between api and website.

handle null expiration date values in view, since they are valid and the

---

admin/view/stylesheet/stylesheet.css
admin/view/template/catalog/mvd_product_form.tpl
admin/view/template/catalog/vendor_form.tpl

Move vendor status to top of 'general' pane so it's easier to find.
Mark vendor status in red if it's 'disabled' or 'pending approval'.

Make vendor status easier for admin to see and set

---

admin/controller/catalog/vendor.php
admin/model/catalog/vendor.php
admin/view/template/catalog/vendor_form.tpl

(by changing name of password field)

Avoid incorrect autofill of vendor password in admin pages

---

admin/controller/catalog/vendor_setting.php
admin/language/english/catalog/vendor_setting.php
admin/view/template/catalog/vendor_setting.tpl
catalog/controller/common/vendor_terms.php

Add specific config setting for app signup terms.
Make API to fetch terms & conditions use this configured value.

App signup policy

---

catalog/view/theme/atr374opc2101/template/checkout/checkout.tpl

when user acknowledges warning or agrees to terms & conditions.

Fix for #206. Add click handlers to reset 'continue' button

---

api/v1/catalog/controller/product/product.php
catalog/controller/product/product_tesitoo_api.php

Reapply of projectwife/tesitoo-opencart#209

Reapply price format corrections

---

vqmod/xml/add_and_delete_product.xml
vqmod/xml/add_location_product_page.xml
vqmod/xml/vendor_name_on_product_page.xml
vqmod/xml/vendor_view.xml
vqmod/xml/weight_class.xml

Fix for #213 
(forgot to apply vqmod changes to new file)

fix vendor id and name

---

api/v1/catalog/controller/vendor/products.php
catalog/controller/product/product_tesitoo_api.php

exact number of decimal places for monetary values in `/vendor/products` and `/product/product/{id}` requests.

Price formatting

---

admin/controller/sale/tesitoo_order.php
admin/view/template/sale/order_form.tpl

Fix #211
should call api against store_url stored in the order record

Fix error showing when admin editing order (on google instance only).

---

admin/view/stylesheet/stylesheet.css

Make buttons green when temporarily clicked.

---

api/v1/catalog/controller/admin/forgot_password.php
api/v1/catalog/controller/product/base/category_base.php

correct the password reset URL sent in the email

Fix password reset

---

admin/view/stylesheet/stylesheet.css

apply rule when no login button shown too

fix logo positioning problem on admin login screen

---

vqmod/xml/waabay_mvd_core_20160101_.xml

(we never want admin / mods to access the old single-vendor-opencart-style product catalog)

Replace regular catalog in admin menu with multi vendor catalog

---

admin/controller/catalog/mvd_product.php
admin/controller/catalog/vdi_product.php

also trim whitespace for both vendor and admin

fill meta title and description for admin-added products
